bedroom_choices = {
    '1':1,
    '2':2,
    '3':3,
    '4':4,
    '5':5,
    '6':6,
    '7':7,
    '8':8,
    '9':9,
    '10':10
}

price_choices = {
    '100000': '$100,000',
    '200000': '$200,000',
    '300000': '$300,000',
    '400000': '$400,000',
    '500000': '$500,000',
    '600000': '$600,000',
    '700000': '$700,000',
    '800000': '$800,000',
    '900000': '$900,000',
    '1000000': '$1M+'
}

county_choices = {
    'MO': 'Mombasa',
    'KW': 'Kwale',
    'KL': 'Kilifi',
    'TR': 'Tana River',
    'LM': 'Lamu',
    'TT': 'Taita taveta',
    'GR': 'Garissa',
    'WJ': 'Wajir',
    'MD': 'Mandera',
    'MS': 'Marsabit',
    'IS': 'Isiolo',
    'MR': 'Meru',
    'TN': 'Tharakanithi',
    'EM': 'Embu',
    'KT': 'Kitui',
    'MA': 'Machakos',
    'MK': 'Makueni',
    'NY': 'Nyandarua',
    'NY': 'Nyeri',
    'KR': 'Kirinyaga',
    'MU': 'Muranga',
    'KI': 'Kiambu',
    'TK': 'Turkana',
    'WP': 'West Pokot',
    'SM': 'Samburu',
    'TN': 'Trans Nzoia',
    "UG": 'Uasin Gishu',
    'El': "Elgeyo Marakwet",
    'ND': 'Nandi',
    'Br': 'Baringo',
    'LK': 'Laikipia',
    'NK': 'Nakuru',
    'KJ': 'Kajiado',
    'KC': 'Kericho',
    'BT': "Bomet",
    'KK': 'Kakamega',
    'VH': 'Vihiga',
    'BN': 'Bungoma',
    'BS': 'Busia',
    'SY': 'SIaya',
    'KS': 'Kisumu',
    'HB': 'Homabay',
    'MI': 'Migori',
    'KII': 'Kisii',
    'NM': 'Nyamira',
    'NA': 'Nairobi',
}